# Generated by Django 6.0.7 on 2026-07-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_parentys_phone_number_students_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='admission_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
