# Generated by Django 6.0.7 on 2026-07-09 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0003_alter_students_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='SchoolClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.schoolclass'),
        ),
    ]
