# Generated by Django 6.0.7 on 2026-07-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('teachers', '0002_remove_teacher_schoolclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='classes', to='teachers.teacher'),
        ),
    ]
