# Generated by Django 6.0.7 on 2026-07-12 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_schoolclass_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='teachers',
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
