# Generated by Django 6.0.7 on 2026-07-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestructure',
            old_name='School_class',
            new_name='school_class',
        ),
    ]
