# Generated by Django 6.0.7 on 2026-07-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_schoolclass_academic_year_and_more'),
        ('teachers', '0004_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='classes.schoolclass'),
        ),
    ]
