# Generated by Django 6.0.7 on 2026-07-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='job',
            field=models.CharField(choices=[('Accountant', 'Accountant'), ('Cleaner', 'Cleaner'), ('Librarian', 'Librarian'), ('Driver', 'Driver'), ('security', 'Security'), ('Cook', 'Cook'), ('Nurse', 'Nurse'), ('Bursar', 'Bursar')], default='nurse', max_length=50),
        ),
    ]
