# Generated by Django 6.0.7 on 2026-07-12 18:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_worker_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='staff_number',
            new_name='employee_number',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='job',
        ),
        migrations.AddField(
            model_name='worker',
            name='hired_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='worker_photos/'),
        ),
        migrations.AddField(
            model_name='worker',
            name='position',
            field=models.CharField(choices=[('Secretary', 'Secretary'), ('Accountant', 'Accountant'), ('Driver', 'Driver'), ('Cook', 'Cook'), ('Security Guard', 'Security Guard'), ('Cleaner', 'Cleaner'), ('Librarian', 'Librarian'), ('Nurse', 'Nurse'), ('Other', 'Other')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
