# Generated by Django 6.0.7 on 2026-07-12 18:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'workers',
            '0003_rename_staff_number_worker_employee_number_and_more'
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.RemoveField(
            model_name='worker',
            name='hired_date',
        ),

        migrations.RemoveField(
            model_name='worker',
            name='photo',
        ),

        migrations.RemoveField(
            model_name='worker',
            name='position',
        ),

        migrations.AddField(
            model_name='worker',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='worker',
            name='job_title',
            field=models.CharField(
                max_length=100,
                default='Worker'
            ),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='worker_profile',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]